SIMPLE_DATE_FORMAT_US = "%m-%d-%Y"
SIMPLE_DATE_FORMAT_EU = "%d-%m-%Y"
SIMPLE_DATE_FORMAT_ISO = "%Y-%m-%d"

SIMPLE_DATE_FORMAT_US_SLASHES = "%m/%d/%Y"
SIMPLE_DATE_FORMAT_EU_SLASHES = "%d/%m/%Y"
SIMPLE_DATE_FORMAT_ISO_SLASHES = "%Y/%m/%d"

FULL_DATE_FORMAT_US = "%m-%d-%Y %I:%M %p"
